### ISSUE TITLE
V2 Release Roadmap

### ISSUE THREAD

**Issue by DevTobias** [DevTobias/ripper#1]
Features
- [ ] English translation file / Language dropdown
- [ ]  Quality of life improvements regarding TV Shows: Persist last metadata, so that you don't have to select the same tv show all over again
- [ ]  Ansible Deployment Playbook
- [ ] Discord Webhook notifications for progress updates
- [ ] Dark mode support
- [ ] Provide prebuilt rust binaries

Bugs
- [ ]  Investigated and fixed bug, where the website crashes and goes completely white after completing the job
